apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newsletter
resources:
  - clickstack.yaml
  - otel-collectors.yaml
  - networkpolicy.yaml
  - postgres.yaml
  - migrate-job.yaml
  - newsletter.yaml
