apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newsletter
resources:
  - namespace.yaml
  - db-app-secret.yaml
  - clickstack-otel-secret.yaml
  - postgres-cluster.yaml
  - logs-collector.yaml
  - migrate-job.yaml
  - newsletter.yaml
